-- DROP TABLE IF EXISTS income;

CREATE TABLE IF NOT EXISTS income (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  date DATETIME NOT NULL,
  name VARCHAR(250) NOT NULL,
  amount INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS expense(
	id INT AUTO_INCREMENT PRIMARY KEY,
	date DATETIME NOT NULL,
	name VARCHAR(250) NOT NULL,
	amount INT NOT NULL
);
